#!/usr/bin/env python3
"""Wrapper script installer for ober.

This module provides a way to install a wrapper script to /usr/local/bin/ober
that finds and executes the real ober binary from wherever it's installed.
"""

import os
import stat
import sys
from pathlib import Path

WRAPPER_SCRIPT = """#!/bin/bash
# Ober wrapper script - finds and runs ober from pipx or venv installation
# Generated by: ober-install-wrapper

# Check common locations for ober
for ober_path in \\
    "/root/.local/bin/ober" \\
    "$HOME/.local/bin/ober" \\
    "/opt/ober/venv/bin/ober" \\
    ; do
    if [ -x "$ober_path" ]; then
        exec "$ober_path" "$@"
    fi
done

echo "Error: ober not found. Install with: sudo pipx install herr-ober" >&2
exit 1
"""


def install_wrapper() -> None:
    """Install the ober wrapper script to /usr/local/bin/ober."""
    if os.geteuid() != 0:
        print("Error: Must run as root to install wrapper script.")
        print("Run: sudo ober-install-wrapper")
        sys.exit(1)

    wrapper_path = Path("/usr/local/bin/ober")

    # Don't overwrite if it's a symlink to an actual ober binary
    if wrapper_path.is_symlink():
        target = wrapper_path.resolve()
        if target.exists() and "ober" in str(target):
            print(f"Symlink already exists: {wrapper_path} -> {target}")
            print("Remove it first if you want to install the wrapper script.")
            sys.exit(1)

    # Write the wrapper script
    wrapper_path.write_text(WRAPPER_SCRIPT)

    # Make it executable
    wrapper_path.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)

    print(f"Installed wrapper script to {wrapper_path}")
    print("You can now use 'sudo ober' from anywhere.")


if __name__ == "__main__":
    install_wrapper()
